Added finnish translation
denysdovhan/vacuum-card pull request #173
Opened 2021-01-13 15:39 UTC by pasiz

Finnish translation for the vacuum card

2021-02-02 14:08 UTC, denysdovhan approved these changes
Thanks for contributing!

2021-02-02 14:09 UTC, denysdovhan requested changes
Wait a minute! 
You should add the localization file in `localize.js` and add the corresponding line in docs!

2021-02-07 21:11 UTC, pasiz commented
Sorry, i forgot to commit those files on git

2021-02-08 10:58 UTC, denysdovhan requested changes
There's no `fi.json` in this PR. Please, test your PR locally before opening a PR 🙏🏻

2021-02-08 10:58 UTC, denysdovhan commented on src/localize.js
> +import * as ko from './translations/fi.json';
`ko` is already declared above. This will cause a syntax error.

2021-02-08 17:44 UTC, denysdovhan approved these changes

2021-02-08 17:54 UTC, merged

2021-02-08 17:54 UTC, denysdovhan commented
Thanks for contributing!