Add norsk nynorsk (Norwegian)
denysdovhan/vacuum-card pull request #199
Opened 2021-03-23 15:13 UTC by petrepa

Added norsk nynorsk (Norwegian), so now both the written Norwegian languages can be supported 😄

2021-04-13 13:43 UTC, denysdovhan requested changes
Please, read contributing guidelines. You have to manually import this file in `localize.js` file

2021-04-13 14:06 UTC, petrepa commented
Woops! That one slipped away 😬  Sorry about that one!

Hopefully fixed now 😅

2021-04-16 16:04 UTC, denysdovhan approved these changes

2021-04-16 16:04 UTC, merged

2021-04-16 16:05 UTC, denysdovhan commented
Thanks for contributing!