Fix for "The websocket command 'camera_thumbnail' has been deprecated".
denysdovhan/vacuum-card pull request #201
Opened 2021-04-05 14:07 UTC by grinstantin

2021-04-05 20:35 UTC, denysdovhan requested changes
Thanks!
Don't forget to update docs!

2021-04-06 12:35 UTC, grinstantin commented
There are no changes in config or description at all.

2021-04-13 13:41 UTC, denysdovhan approved these changes

2021-04-13 13:41 UTC, merged

2021-04-13 13:41 UTC, denysdovhan commented
Thanks for contributing!