Update he.json
denysdovhan/vacuum-card pull request #219
Opened 2021-05-20 20:54 UTC by tzagim

2021-06-07 15:06 UTC, denysdovhan requested changes

2021-06-07 15:06 UTC, denysdovhan commented on src/vacuum-card.js
> +              icon="mdi:crosshairs-gps"
Please, do not change that. See #182

2021-06-09 12:34 UTC, tzagim commented on src/vacuum-card.js
> +              icon="mdi:crosshairs-gps"
Ok

2021-06-09 12:38 UTC, tzagim commented
@denysdovhan
BTW, In RTL languages this line"
"margin-**left**: calc(20px + 9px); /* size + margin of spinner */"
in style.js

should be 
"margin-**right**: calc(20px + 9px); /* size + margin of spinner */"

2021-06-11 16:56 UTC, merged