Add Option to Hide Start/Locate Buttons
denysdovhan/vacuum-card pull request #245
Opened 2021-07-18 08:51 UTC by rsegers

This PR add the option to hide the Start and/or Locate buttons on the toolbar. The Locate button is not supported by some vacuums and therefore has no added value. The Start button may not function well for homes with advanced layouts or schedules, and therefore use a custom action to start for example a daily routine, or a certain room.

The toolbar actions will align to the center when both the Start and Locate button are hidden.

The following two config items are added:

| Name                |   Type    | Default      | Description                                                             |
| ------------------- | :-------: | ------------ | ----------------------------------------------------------------------- |
| `show_startbutton`  | `boolean` | `true`       | Show start button on toolbar.                                           |
| `show_locatebutton` | `boolean` | `true`       | Show locate button on toolbar.                                          |

The config is also added to the visual editor.

<img width="382" alt="idle" src="https://user-images.githubusercontent.com/3670848/126061264-a1595e6a-8aca-4fb9-b637-756a8e61da51.png">
<img width="375" alt="docked no buttons" src="https://user-images.githubusercontent.com/3670848/126061266-02df9c0b-2aa5-4e33-a565-ebd20011c65a.png">
<img width="376" alt="docked start" src="https://user-images.githubusercontent.com/3670848/126061267-2802cc36-1e28-4e90-962b-c44e4079b7a0.png">
<img width="367" alt="config" src="https://user-images.githubusercontent.com/3670848/126061317-786cdc29-f6dc-46ee-bc1f-46392435de0d.png">

Addresses issue #194

2021-11-05 22:24 UTC, denysdovhan requested changes

2021-11-05 22:24 UTC, denysdovhan commented on README.md
> +| `show_startbutton`  | `boolean` | `true`       | Show start button on toolbar.                                           |
Let's make it `show_start_button` and `show_locate_button`

2021-11-05 22:24 UTC, denysdovhan commented on src/vacuum-card.js
> +          <ha-icon-button
This is deprecated in the latest HA. Needs to be updated.

2021-11-08 10:00 UTC, rsegers commented
Thanks for the review! The PR had been updated

2022-02-13 20:11 UTC, dark-spider commented
Hello. When will the card be updated with this feature? Thank you

2022-02-13 20:20 UTC, denysdovhan commented
FYI: Russia have a huge military buildup around the borders of my country. It’s getting hot, countries are evacuating their embassies and flights are getting canceled.

I’m busy with packing my stuff to move out from Kyiv for some time in order to keep me and my family safe from possible war actions.

Sorry I’m not going to work it this projects in the nearest weeks. Thanks for understanding 🙏🏻

Please, spread #StandWithUkraine and try to make your government representatives know that Ukraine needs help.

2022-04-27 09:34 UTC, emufan commented
Would be great to have this for any button and not for the listed two. As is not merged for now, perhaps this can be improved?

E.G. I want to hide all, but show my shortcut ones, e.g. to set another icon than the standard ones.

2022-06-28 20:36 UTC, 17hoehbr commented
I would also love an option to hide the stop button as it doesn't work on my vacuum.

2023-07-09 19:03 UTC, closed without merging

2025-03-09 23:51 UTC, yummypho commented
I have a Wyze vacuum, and the Locate doesn't seem to work.  It would be great to get this PR accepted so we can hide feature not relevant.   Thx!