Update Polish translation
denysdovhan/vacuum-card pull request #294
Opened 2021-11-18 18:11 UTC by MrBartusek

Add missing keys to Polish translation and update strings with invalid letter case

2021-11-18 18:11 UTC, MrBartusek commented on src/translations/pl.json
> +    "edge": "Sprzątanie Brzegowe",
This's a wired way to translate it but I guess it's good enough

2021-12-08 19:44 UTC, denysdovhan requested changes
Could you please add those statuses to English version as well?

2021-12-08 20:21 UTC, MrBartusek commented
@denysdovhan I'm not sure about which statuses are you exactly talking about? This is the exact list of messages from the `en.json` file at the time of creating this PR.

2022-04-20 19:37 UTC, denysdovhan commented
Already in master. Resolved.

2022-04-20 19:37 UTC, closed without merging