Update Italian language
denysdovhan/vacuum-card pull request #302
Opened 2021-11-29 08:45 UTC by MagicOneIta

I have add some missing command

2021-12-08 19:31 UTC, denysdovhan approved these changes

2021-12-08 19:33 UTC, denysdovhan requested changes
You have a typo in JSON, please fix it.

2021-12-09 08:10 UTC, MagicOneIta commented
I amSorry, I fixed it

2022-04-20 19:30 UTC, denysdovhan approved these changes

2022-04-20 19:31 UTC, merged