Update en.json - mijia.vacuum.v2
denysdovhan/vacuum-card pull request #572
Opened 2023-08-07 10:23 UTC by Szesi111

Missing source string for mijia.vacuum.v2

2023-08-07 10:27 UTC, Szesi111 commented
"stanrd" is a valid mistyped word by mijia.vacuum.v2

2023-09-04 12:30 UTC, denysdovhan requested changes

2023-09-04 12:30 UTC, denysdovhan commented on src/translations/en.json
> +    "stanrd": "Standard",
Maybe this?

```suggestion
    "standard": "Standard",
```

2023-12-10 21:00 UTC, denysdovhan commented
No response

2023-12-10 21:00 UTC, closed without merging